### ISSUE TITLE
roles plugins getRole maximum call stack exceeded

### ISSUE THREAD

**Issue by morko** [saviola777/hhm-plugins#13]
When trying to use the `getRole` method with `getRole('admin', { offlinePlayers: true }` haxroomie prints out this error:

```
2019-08-09 10:00:16 [error]: Error: Evaluation failed: RangeError: Maximum call stack size exceeded
    at Proxy.hasOwnProperty (<anonymous>)
    at Proxy.getPluginSpec (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:18015:17)
    at Proxy.getConfig (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:17912:31)
    at hasRole (eval at _executePlugin (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:14526:18), <anonymous>:241:15)
    at getRole (eval at _executePlugin (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:14526:18), <anonymous>:204:22)
    at eval (eval at _executePlugin (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:14526:18), <anonymous>:222:25)
    at Array.forEach (<anonymous>)
    at getRoles (eval at _executePlugin (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:14526:18), <anonymous>:221:55)
    at getRole (eval at _executePlugin (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:14526:18), <anonymous>:209:28)
    at eval (eval at _executePlugin (https://hhm.surge.sh/releases/hhm-git.js?_=1565344799505:14526:18), <anonymous>:222:25)
    at ExecutionContext.evaluateHandle (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/ExecutionContext.js:121:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/helper.js:110:27)
    at ExecutionContext.evaluate (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/ExecutionContext.js:48:31)
    at ExecutionContext.<anonymous> (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/helper.js:111:23)
    at DOMWorld.evaluate (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/DOMWorld.js:105:20)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  -- ASYNC --
    at Frame.<anonymous> (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/helper.js:110:27)
    at Page.evaluate (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/Page.js:809:43)
    at Page.<anonymous> (/home/oskari/workspace/node/haxroomie/node_modules/puppeteer/lib/helper.js:111:23)
    at PluginController.getRole (/home/oskari/workspace/node/haxroomie/src/room/PluginController.js:291:22)
    at processTicksAndRejections (internal/process/task_queues.js:86:5) 
```

**Comment by saviola777** [comment]
This is now fixed.
